name: islamapp
description: "A comprehensive Islamic application with Quran, Adhkar, Prayer Times, Qibla, and Hadith."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # <-- انقلها إلى هنا
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.0.5

  # UI & Animations
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  animate_do: ^3.3.4
  percent_indicator: ^4.2.3


  # Prayer Times & Qibla
  adhan: ^2.0.0-nullsafety.2

  geolocator: ^13.0.4


  flutter_qiblah: ^3.1.0+1
  #qibla_compass: ^2.0.2
  # Local Storage
  shared_preferences: ^2.2.2

  # HTTP for future API calls
  http: ^1.1.0

  scrollable_positioned_list: ^0.3.8
  hijri: ^3.0.0
  audioplayers: ^6.5.0
  share_plus: ^11.0.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/v.jp
  g"


  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/json/hadith/
    - assets/json/surahs/
    - assets/json/quran_juz_map.json

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/UthmanicHafs1-Ver09_2.otf